server:
  port: 6001
spring:
  application:
    name: pms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: dev
        group: pms
      config:
        namespace: dev
        group: pms
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
